# config version, required
version: {{ .Version }}

# the site title
title: {{ .Title }}

# Copyright notice that themes may display in the footer
copyright: {{ .Title }} {{ .Year }}

# Optional prefix for all URIs (/index.html becomes /docs/index.html)
#  this is useful when the site is hosted in a subdirectory.
#  Default: empty
# uri_prefix: /docs

# Directory where the generated site will be placed.
#  Default: public
# public_directory: public

# Language code for the site (in html lang attribute)
#  Default: en
# language: en

# Search index configuration
search:
  # Minimum keyword length for the search index
  min_keyword_length: 3
  # List of words to ignore in the search index
  stop_words: ["the", "and", "how"]

# Theme configuration
theme:
  # Path to the theme directory
  path: themes/base
  # Arguments that may be used by specific themes.
  # args:
  #  style: dark

# Menu configuration
menu:
  # if true, adds the URI prefix to the href of each item that doesn't start with http
  #  Default: true
  #  auto_prefix: true

  # Items to appear in the menu or sitemap.
  items:
    - title: Home
      href: /index.html
    - title: Posts
      href: /post-list-1.html
    - title: Example
      children:
        - title: Gotoweb Documentation
          href: https://gotoweb.nullism.com
          target: _blank
    - title: Search
      href: /search.html