title: Gotoweb Documentation

# public_directory: public
# uri_prefix: /docs

copyright: "2024 Gotoweb"
version: 1

index:
  min_keyword_length: 3
  stopwords: ["the", "and", "how"]

theme:
  path: ../themes/base

  args:
    style: dark

menu:
  auto_prefix: true
  items:
    - title: Home
      href: /index.html
    - title: Posts
      href: /posts-1.html
      children:
        - title: Sub
          children:
            - title: Hello 2
              href: /posts/sub/hello2.html
        - title: Posts 1
          href: /posts-1.html
        - title: Posts 2
          href: /posts-2.html
    - title: Search
      href: /search.html
    - title: Google
      href: https://google.com