name: Gotoweb Documentation

# public_directory: public
# uri_prefix: /docs

copyright: "2024 Gotoweb"
version: 1

index:
  min_keyword_length: 3
  stopwords: ["the", "and", "how"]

theme:
  path: ../themes/base

  args:
    style: dark

