title: Gotoweb Documentation

public_directory: public/docs
uri_prefix: /docs
# language: en

copyright: "2024 Gotoweb"
version: 1

search:
  min_keyword_length: 3
  stop_words: ["the", "and", "how"]

# Set homepage
homepage: post-list-1.html

theme:
  path: ../themes/dark

  args:
    style: dark

menu:
  auto_prefix: true
  items:
    - title: Home
      href: /index.html
    - title: Authoring
      href: /search.html?tag=authoring
    - title: Theming
      href: /search.html?tag=theming
      children:
        - title: Create a Theme
          href: /theme/create.html
        - title: Posts 2
          href: /post-list-2.html
    - title: Search
      href: /search.html
    - title: Google
      href: https://google.com