
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 10

    - uses: gwatts/go-coverage-action@v2
      id: coverage
      with:
        # Optional coverage threshold
        # use fail-coverage to determine what should happen below this threshold
        # coverage-threshold: 80

        # collect coverage for all packages beyond the one under test
        cover-pkg: ./...

        # # Ignore code-generated files when calculating coverage totals
        # ignore-pattern: |
        #   \.pb\.go$
        #   \_string\.go$

        # A url that the html report will be accessible at, once your
        # workflow uploads it.  Used in the pull request comment.
        # report-url: https://artifacts.example.com/go-coverage/${{ github.ref_name}}.html
